services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai_knowledge_assistant
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres
      - qdrant
    command: uvicorn app_dash:app_dash --host 0.0.0.0 --port 8001 --reload

  postgres:
    image: postgres:14
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_KEY: ${POSTGRESQL_KEY}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_DB_NAME: ${POSTGRESQL_DB_NAME}
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant_vector_db
    ports:
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

  ollama:
    image: ollama/ollama
    container_name: ollama_mistral
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  postgres_data:
  qdrant_data:
  ollama_data: