name: ai_knowledge_assistant
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - ipython
  - jupyterlab
  - matplotlib
  - notebook
  - numpy
  - pandas
  - scikit-learn
  - ruff
  - pytest
  - pip:
    - python-dotenv
    - awscli
    - -e .